import * as THREE from 'three';

const SIZE = 512;
let cachedMaterials;
const rng = seed => () => { seed |= 0; seed = seed + 0x6d2b79f5 | 0; let value = Math.imul(seed ^ seed >>> 15, 1 | seed); value = value + Math.imul(value ^ value >>> 7, 61 | value) ^ value; return ((value ^ value >>> 14) >>> 0) / 4294967296; };
function texture(draw, seed) { const canvas=document.createElement('canvas');canvas.width=canvas.height=SIZE;draw(canvas.getContext('2d'),rng(seed));const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;map.wrapS=map.wrapT=THREE.RepeatWrapping;map.minFilter=THREE.LinearMipmapLinearFilter;map.magFilter=THREE.LinearFilter;map.anisotropy=8;return map; }
function wood(ctx,random){const data=ctx.createImageData(SIZE,SIZE);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const warp=17*Math.sin(y*.021)+9*Math.sin(y*.057+1.4),dx=x-SIZE*.47+warp,dy=(y-SIZE*.52)*1.3;const rings=Math.sin(Math.hypot(dx,dy)*.105+1.2*Math.sin(y*.035)),grain=Math.sin((x+8*Math.sin(y*.08))*.17)*.22,shade=rings*16+grain*12+(random()-.5)*12,i=(y*SIZE+x)*4;data.data.set([174+shade,104+shade*.62,55+shade*.32,255],i);}ctx.putImageData(data,0,0);ctx.globalAlpha=.2;ctx.strokeStyle='#542813';ctx.lineWidth=2;for(let i=0;i<18;i++){const y=random()*SIZE;ctx.beginPath();ctx.moveTo(0,y);ctx.bezierCurveTo(150,y+random()*40-20,350,y+random()*50-25,SIZE,y+random()*30-15);ctx.stroke();}}
function stone(ctx,random){ctx.fillStyle='#777b7d';ctx.fillRect(0,0,SIZE,SIZE);for(let scale=0;scale<3;scale++){const count=[55,150,650][scale];for(let i=0;i<count;i++){const r=(3-scale)*5+random()*[34,13,3][scale];ctx.fillStyle=random()>.48?`rgba(190,194,193,${.08+random()*.18})`:`rgba(35,39,41,${.08+random()*.2})`;ctx.beginPath();ctx.ellipse(random()*SIZE,random()*SIZE,r,r*(.35+random()),random()*Math.PI,0,Math.PI*2);ctx.fill();}}ctx.strokeStyle='rgba(42,45,46,.18)';for(let i=0;i<9;i++){let x=random()*SIZE,y=random()*SIZE;ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<4;j++){x+=random()*35-17;y+=random()*28;ctx.lineTo(x,y);}ctx.stroke();}}
function paper(ctx,random){ctx.fillStyle='#eee7d5';ctx.fillRect(0,0,SIZE,SIZE);for(let i=0;i<2200;i++){ctx.strokeStyle=random()>.5?'rgba(156,139,105,.09)':'rgba(255,255,255,.18)';ctx.lineWidth=.5+random();const x=random()*SIZE,y=random()*SIZE,l=2+random()*14;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+l,y+random()*4-2);ctx.stroke();}for(let i=0;i<12;i++){ctx.strokeStyle='rgba(145,130,105,.10)';ctx.lineWidth=1+random()*2;ctx.beginPath();const x=random()*SIZE,y=random()*SIZE;ctx.moveTo(x,y);ctx.quadraticCurveTo(x+70,y+random()*35-17,x+150,y+random()*25-12);ctx.stroke();}}
export function getBallMaterials(){if(!cachedMaterials)cachedMaterials={wood:new THREE.MeshStandardMaterial({map:texture(wood,1701),roughness:.7,metalness:.03}),stone:new THREE.MeshStandardMaterial({map:texture(stone,2702),roughness:.95,metalness:.02}),paper:new THREE.MeshStandardMaterial({map:texture(paper,3703),roughness:.88,metalness:0})};return cachedMaterials;}
