import * as THREE from 'three'; import { CONFIG } from '../config.js'; import { PhysicsWorld } from './PhysicsWorld.js'; import { InputManager } from './InputManager.js'; import { FollowCamera } from './FollowCamera.js'; import { BallController } from '../player/BallController.js'; import { Level01 } from '../levels/Level01.js'; import { HUD } from '../ui/HUD.js';
export class Game {
  constructor(root){this.root=root;this.state='PLAYING';this.lives=CONFIG.initialLives;this.elapsed=0;this.accumulator=0;this.last=0;}
  async start(){this.physics=new PhysicsWorld();await this.physics.init();this.setupScene();this.input=new InputManager();this.level=new Level01(this.scene,this.physics);this.ball=new BallController(this.scene,this.physics);this.cameraRig=new FollowCamera(this.camera);this.cameraRig.snap(this.ball.mesh.position);this.respawn={...CONFIG.spawn};this.hud=new HUD(this.root,()=>location.reload());addEventListener('resize',()=>this.resize());this.renderer.setAnimationLoop(t=>this.frame(t));}
  setupScene(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x91b8d1);this.scene.fog=new THREE.Fog(0x91b8d1,35,90);this.camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,150);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.root.append(this.renderer.domElement);this.resize();this.scene.add(new THREE.HemisphereLight(0xd7efff,0x263047,2.1));const sun=new THREE.DirectionalLight(0xfff2d0,3);sun.position.set(-12,18,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-50;this.scene.add(sun);const clouds=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshBasicMaterial({color:0x536d89,transparent:true,opacity:.35}));clouds.rotation.x=-Math.PI/2;clouds.position.y=-12;this.scene.add(clouds);}
  resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
  groundContact(){const p=this.ball.body.translation(),ray=new this.physics.RAPIER.Ray({x:p.x,y:p.y,z:p.z},{x:0,y:-1,z:0});const hit=this.physics.world.castRayAndGetNormal(ray,CONFIG.ball.radius+.16,true,undefined,undefined,undefined,this.ball.body);return hit?{normalY:Math.abs(hit.normal.y)}:null;}
  fixedUpdate(){if(this.state==='PLAYING')this.ball.update(this.input,this.groundContact());this.physics.step();this.level.seesaw.sync();this.ball.sync();const p=this.ball.body.translation();if(this.state==='PLAYING'){if(this.level.checkpoint.check(p)){this.respawn={x:0,y:3,z:-24};}if(this.level.finish.contains(p)){this.state='LEVEL_COMPLETE';this.ball.clearExternalLoads();this.ball.body.setLinvel({x:0,y:0,z:0},true);this.hud.show('Level Complete',`Time ${this.elapsed.toFixed(1)} seconds`);}else if(p.y<CONFIG.respawnHeight)this.beginRespawn();}}
  beginRespawn(){this.state='RESPAWNING';this.lives--;this.ball.clearExternalLoads();this.ball.body.setLinvel({x:0,y:0,z:0},true);setTimeout(()=>{if(this.lives<=0){this.state='GAME_OVER';this.hud.show('Game Over','The sky claims another run.');}else{this.ball.teleport(this.respawn);this.cameraRig.snap(this.ball.mesh.position);this.state='PLAYING';}},CONFIG.respawnDelay*1000);}
  frame(ms){const dt=Math.min((ms-this.last)/1000||0,.1);this.last=ms;if(this.state==='PLAYING')this.elapsed+=dt;this.accumulator+=dt;let steps=0;while(this.accumulator>=CONFIG.fixedTimeStep&&steps++<CONFIG.maxSubSteps){this.fixedUpdate();this.accumulator-=CONFIG.fixedTimeStep;}this.cameraRig.update(this.ball.mesh.position,dt);this.hud.update(this.elapsed,this.lives,this.level.checkpoint.active);this.renderer.render(this.scene,this.camera);}
}
