import * as THREE from 'three'; import { CONFIG } from '../config.js'; import { PhysicsWorld } from './PhysicsWorld.js'; import { InputManager } from './InputManager.js'; import { FollowCamera } from './FollowCamera.js'; import { BallController } from '../player/BallController.js'; import { Level01 } from '../levels/Level01.js'; import { HUD } from '../ui/HUD.js'; import { SafePositionTracker } from './SafePositionTracker.js'; import { StuckDetector } from './StuckDetector.js';
export class Game {
  constructor(root){this.root=root;this.state='PLAYING';this.lives=CONFIG.initialLives;this.elapsed=0;this.accumulator=0;this.last=0;}
  get lastSafePosition(){return this.safePositions?.position??{...CONFIG.spawn};}
  setState(next){if(this.state===next)return;if(CONFIG.debugPhysics)console.debug(`[GameState] ${this.state} -> ${next}`);this.state=next;}
  async start(){this.physics=new PhysicsWorld();await this.physics.init();this.setupScene();this.input=new InputManager(this.renderer.domElement);this.level=new Level01(this.scene,this.physics);this.ball=new BallController(this.scene,this.physics);this.cameraRig=new FollowCamera(this.camera);this.cameraRig.snap(CONFIG.spawn);this.respawn={...CONFIG.spawn};this.hud=new HUD(this.root,()=>location.reload());this.safePositions=new SafePositionTracker(this.physics,this.ball,CONFIG.spawn);this.stuckDetector=new StuckDetector();this.unstuckCooldown=0;this.hud.setBallType(this.ball.currentType);addEventListener('resize',()=>this.resize());this.renderer.setAnimationLoop(t=>this.frame(t));}
  setupScene(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x91b8d1);this.scene.fog=new THREE.Fog(0x91b8d1,35,90);this.camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,150);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.root.append(this.renderer.domElement);this.resize();this.scene.add(new THREE.HemisphereLight(0xd7efff,0x263047,2.1));const sun=new THREE.DirectionalLight(0xfff2d0,3);sun.position.set(-12,18,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-25;sun.shadow.camera.right=25;sun.shadow.camera.top=25;sun.shadow.camera.bottom=-50;this.scene.add(sun);const clouds=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshBasicMaterial({color:0x536d89,transparent:true,opacity:.35}));clouds.rotation.x=-Math.PI/2;clouds.position.y=-12;this.scene.add(clouds);}
  resize(){this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);}
  groundContact(){const p=this.ball.body.translation(),ray=new this.physics.RAPIER.Ray({x:p.x,y:p.y,z:p.z},{x:0,y:-1,z:0});const hit=this.physics.world.castRayAndGetNormal(ray,CONFIG.ball.radius+.16,true,undefined,undefined,undefined,this.ball.body);return hit?{normalY:hit.normal.y,fixed:Boolean(hit.collider.parent()?.isFixed()),collider:hit.collider}:null;}
  fixedUpdate(){const ground=this.groundContact();if(this.state==='PLAYING'){this.ball.update(this.cameraRelativeMovement(),ground,this.state);this.level.windZone.update(this.ball.body);}this.physics.step();this.level.seesaw.sync();this.ball.sync();const p=this.ball.body.translation();if(this.state==='PLAYING'){this.safePositions.update({state:this.state,ground,inWindZone:this.level.windZone.contains(p),dt:CONFIG.fixedTimeStep});for(const pad of this.level.transformPads)pad.update(p,type=>this.setBallType(type));if(this.level.checkpoint.check(p)){this.respawn={x:0,y:2.265,z:-24};}if(this.level.finish.contains(p)){this.setState('LEVEL_COMPLETE');this.ball.clearExternalLoads();this.ball.body.setLinvel({x:0,y:0,z:0},true);this.hud.show('Level Complete',`Time ${this.elapsed.toFixed(1)} seconds`);}else if(p.y<CONFIG.respawnHeight)this.beginRespawn();}}
  setBallType(type){if(this.ball.setBallType(type)){this.hud.setBallType(type);this.hud.flashForm(type);return true;}return false;}
  cameraRelativeMovement(){const input=this.input.movement,{forward,right}=this.cameraRig.getHorizontalBasis();const x=right.x*input.x-forward.x*input.z,z=right.z*input.x-forward.z*input.z,length=Math.hypot(x,z);return length>1?{x:x/length,z:z/length}:{x,z};}
  beginRespawn(){this.setState('RESPAWNING');this.lives--;this.ball.clearExternalLoads();this.ball.body.setLinvel({x:0,y:0,z:0},true);setTimeout(()=>{if(this.lives<=0){this.setState('GAME_OVER');this.hud.show('Game Over','The sky claims another run.');}else{this.ball.teleport(this.respawn);this.ball.sync();this.cameraRig.snap(this.ball.mesh.position);this.setState('PLAYING');}},CONFIG.respawnDelay*1000);}
  unstuck(){if(this.state!=='PLAYING'||this.unstuckCooldown>0)return false;const p=this.safePositions.position;this.ball.teleport({x:p.x,y:p.y+.08,z:p.z});this.ball.body.wakeUp();this.ball.sync();this.cameraRig.snap(this.ball.mesh.position);this.stuckDetector.reset(p);this.hud.setStuckHint(false);this.unstuckCooldown=1;return true;}
  frame(ms){const dt=Math.min((ms-this.last)/1000||0,.1);this.last=ms;this.unstuckCooldown=Math.max(0,this.unstuckCooldown-dt);if(this.input.consumeUnstuck())this.unstuck();if(this.state==='PLAYING')this.elapsed+=dt;this.accumulator+=dt;let steps=0;while(this.accumulator>=CONFIG.fixedTimeStep&&steps++<CONFIG.maxSubSteps){this.fixedUpdate();this.accumulator-=CONFIG.fixedTimeStep;}this.level.windZone.updateVisual(dt);const p=this.ball.body.translation(),v=this.ball.body.linvel(),move=this.input.movement;const excluded=this.level.windZone.contains(p)||Math.hypot(p.x-CONFIG.spawn.x,p.z-CONFIG.spawn.z)<1.1||(this.level.checkpoint.active&&Math.hypot(p.x-this.respawn.x,p.z-this.respawn.z)<1.1);this.hud.setStuckHint(this.stuckDetector.update({state:this.state,movingInput:Boolean(move.x||move.z),position:p,horizontalSpeed:Math.hypot(v.x,v.z),dt,excluded}));this.cameraRig.update(this.ball.mesh.position,dt,this.input);this.hud.update(this.elapsed,this.lives,this.level.checkpoint.active);this.renderer.render(this.scene,this.camera);}
}
